name: national_generation_capacity

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.7
  - notebook
  - pandas
  - numpy
  - openpyxl
  - xlrd
  - pyyaml
  - nb_conda_kernels
  - bokeh=1.4



